/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */

export type AuthStatusGuestStatus =
  (typeof AuthStatusGuestStatus)[keyof typeof AuthStatusGuestStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthStatusGuestStatus = {
  guest: "guest"
} as const;
