/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */

export type AuthStatusUserStatus =
  (typeof AuthStatusUserStatus)[keyof typeof AuthStatusUserStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthStatusUserStatus = {
  admin: "admin",
  owner: "owner",
  customer: "customer"
} as const;
