/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */
import type { AuthStatusGuest } from "./authStatusGuest";
import type { AuthStatusUser } from "./authStatusUser";

export type AuthStatus = AuthStatusGuest | AuthStatusUser;
