/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */
import type { AuthStatusUserStatus } from "./authStatusUserStatus";

export interface AuthStatusUser {
  has_verified_email: boolean;
  id: number;
  status: AuthStatusUserStatus;
}
