/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */
import type { AuthStatusGuestStatus } from "./authStatusGuestStatus";

export interface AuthStatusGuest {
  status: AuthStatusGuestStatus;
}
