/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */

export type CreateShopErrorErrors = {
  area_id?: string[];
  detail?: string[];
  genre_id?: string[];
  image?: string[];
  name?: string[];
};
