/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */
import type { AreaData } from "./areaData";
import type { CustomerShopDataFavoriteStatus } from "./customerShopDataFavoriteStatus";
import type { GenreData } from "./genreData";

/**
 * 顧客向け飲食店情報
 */
export interface CustomerShopData {
  area: AreaData;
  /** 飲食店詳細 */
  detail: string;
  /** お気に入りステータス */
  favorite_status: CustomerShopDataFavoriteStatus;
  genre: GenreData;
  /** 飲食店ID */
  id: number;
  /** 画像URL */
  image_url: string;
  /** 飲食店名 */
  name: string;
}
