/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */

/**
 * お気に入りステータス
 */
export type CustomerShopDataFavoriteStatus =
  (typeof CustomerShopDataFavoriteStatus)[keyof typeof CustomerShopDataFavoriteStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerShopDataFavoriteStatus = {
  unknown: "unknown",
  marked: "marked",
  unmarked: "unmarked"
} as const;
