/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */

/**
 * ジャンル情報
 */
export interface GenreData {
  /** ジャンルID */
  id: number;
  /** ジャンル名 */
  name: string;
}
