/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */
import type { GetAreas200ResponseAreasItem } from "./getAreas200ResponseAreasItem";

export type GetAreas200Response = {
  areas: GetAreas200ResponseAreasItem[];
};
