/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */

export type GetAuthStatus200ResponseStatus =
  (typeof GetAuthStatus200ResponseStatus)[keyof typeof GetAuthStatus200ResponseStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAuthStatus200ResponseStatus = {
  guest: "guest",
  customer: "customer"
} as const;
