/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */
import type { GetAuthStatus200ResponseStatus } from "./getAuthStatus200ResponseStatus";

export type GetAuthStatus200Response = {
  id?: number;
  status: GetAuthStatus200ResponseStatus;
};
