/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */
import type { AuthStatus } from "./authStatus";

/**
 * 認証状態取得成功
 */
export type GetAuthStatus200Response = AuthStatus;
