/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */
import type { ReservationData } from "./reservationData";

export type GetCustomerReservations200Response = {
  data: ReservationData[];
};
