/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */
import type { PageQueryParameter } from "./pageQueryParameter";

export type GetCustomerFavoritesParams = {
  /**
   * ページ番号
   */
  page?: PageQueryParameter;
};
