/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */
import type { GetCustomerFavorites200ResponseAllOf } from "./getCustomerFavorites200ResponseAllOf";
import type { Pagination } from "./pagination";

export type GetCustomerFavorites200Response = Pagination &
  GetCustomerFavorites200ResponseAllOf;
