/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */
import type { OwnerShopData } from "./ownerShopData";

export type GetOwnerShops200Response = {
  data: OwnerShopData[];
};
