/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */
import type { GetOwnerShopReservations200ResponseAllOf } from "./getOwnerShopReservations200ResponseAllOf";
import type { Pagination } from "./pagination";

export type GetOwnerShopReservations200Response = Pagination &
  GetOwnerShopReservations200ResponseAllOf;
