/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */
import type { GetShopReviews200ResponseAllOf } from "./getShopReviews200ResponseAllOf";
import type { Pagination } from "./pagination";

export type GetShopReviews200Response = Pagination &
  GetShopReviews200ResponseAllOf;
