/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */

export type GetShops200ResponseAllOfDataItemFavoriteStatus =
  (typeof GetShops200ResponseAllOfDataItemFavoriteStatus)[keyof typeof GetShops200ResponseAllOfDataItemFavoriteStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetShops200ResponseAllOfDataItemFavoriteStatus = {
  unknown: "unknown",
  marked: "marked",
  unmarked: "unmarked"
} as const;
