/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */
import type { GetShops200ResponseAllOf } from "./getShops200ResponseAllOf";
import type { Pagination } from "./pagination";

export type GetShops200Response = Pagination & GetShops200ResponseAllOf;
