/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */
import type { ShopData } from "./shopData";

/**
 * 飲食店情報取得成功
 */
export type GetShop200Response = ShopData;
