/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */
import type { GetShops200ResponseAllOfDataItemFavoriteStatus } from "./getShops200ResponseAllOfDataItemFavoriteStatus";

export type GetShops200ResponseAllOfDataItem = {
  area: string;
  favorite_status: GetShops200ResponseAllOfDataItemFavoriteStatus;
  genre: string;
  id: number;
  image_url: string;
  name: string;
};
