/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */
import type { PaginationDataItem } from "./paginationDataItem";
import type { PaginationLinks } from "./paginationLinks";
import type { PaginationMeta } from "./paginationMeta";

/**
 * ページネーション
 */
export interface Pagination {
  /** ページネーション結果 */
  data: PaginationDataItem[];
  /** ページネーションリンク */
  links: PaginationLinks;
  /** ページネーションメタ情報 */
  meta: PaginationMeta;
}
