/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */
import type { PaginationLinks } from "./paginationLinks";
import type { PaginationMeta } from "./paginationMeta";

/**
 * ページネーション
 */
export interface Pagination {
  links: PaginationLinks;
  meta: PaginationMeta;
}
