/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */
import type { ReservationError } from "./reservationError";

/**
 * 飲食店詳細ページの予約追加のバリデーションエラー
 */
export type PostCustomerShopReservations422Response = ReservationError;
