/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */
import type { PostAuthLogin422ResponseErrors } from "./postAuthLogin422ResponseErrors";

export type PostAuthLogin422Response = {
  errors: PostAuthLogin422ResponseErrors;
  message: string;
};
