/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */
import type { PostAuthRegister422ResponseErrorsItem } from "./postAuthRegister422ResponseErrorsItem";

export type PostAuthRegister422Response = {
  errors: PostAuthRegister422ResponseErrorsItem[];
  message: string;
};
