/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */
import type { ExpiresQueryParameter } from "./expiresQueryParameter";
import type { SignatureQueryParameter } from "./signatureQueryParameter";

export type PostReservationCheckinParams = {
  /**
   * 署名
   */
  signature: SignatureQueryParameter;
  /**
   * 有効期限
   */
  expires?: ExpiresQueryParameter;
};
