/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */
import type { PostAuthLogin422ResponseErrorsItem } from "./postAuthLogin422ResponseErrorsItem";

export type PostAuthLogin422Response = {
  errors: PostAuthLogin422ResponseErrorsItem[];
  message: string;
};
