/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */

export type PostReservationPaymentBody = {
  /** 確認トークンID */
  confirmation_token_id: string;
};
