/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */

export type PostOwnerShopsBody = {
  /** エリア */
  area: string;
  /** 詳細 */
  detail: string;
  /** ジャンル */
  genre: string;
  /** 画像 */
  image: Blob;
  /** 店舗名 */
  name: string;
};
