/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */

export type PostAuthRegisterBody = {
  /** メールアドレス */
  email: string;
  /** 顧客名 */
  name: string;
  /** パスワード */
  password: string;
};
