/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */
import type { CreateShopError } from "./createShopError";

/**
 * 店舗代表者別店舗登録のバリデーションエラー
 */
export type PostOwnerShops422Response = CreateShopError;
