/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */
import type { PostShopReviewsBodyComment } from "./postShopReviewsBodyComment";

export type PostShopReviewsBody = {
  /** コメント */
  comment?: PostShopReviewsBodyComment;
  /** 評価 */
  rating: number;
};
