/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */
import type { ReservationError } from "./reservationError";

/**
 * マイページの予約変更のバリデーションエラー
 */
export type PutCustomerReservation422Response = ReservationError;
