/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */

export type PutCustomerReservationBody = {
  /** 予約人数 */
  number_of_guests: number;
  /** 予約日時 */
  reserved_at: string;
};
