/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Rese
 * Rese API
 * OpenAPI spec version: 0.0.1
 */

/**
 * レビュー情報
 */
export interface ShopReviewData {
  /** コメント */
  comment: string;
  /** 顧客名 */
  customer_name: string;
  /** レビューID */
  id: number;
  /** 評価 */
  rating: number;
}
