name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - run: aws s3api head-bucket --bucket ${{ secrets.AWS_S3_BUCKET_NAME }}

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - id: cache-restore-dev-depends
        uses: actions/cache/restore@v4
        with:
          path: "**/node_modules"
          key: dev-depends-node20-${{ hashFiles('package-lock.json') }}

      - if: steps.cache-restore-dev-depends.outputs.cache-hit != 'true'
        run: npm ci

      - if: steps.cache-restore-dev-depends.outputs.cache-hit != 'true'
        id: cache-save-dev-depends
        uses: actions/cache/save@v4
        with:
          path: "**/node_modules"
          key: dev-depends-node20-${{ hashFiles('package-lock.json') }}

      - run: npm run test

      - run: npm run build

      - run: aws s3 sync dist/ s3://${{ secrets.AWS_S3_BUCKET_NAME }}
